### ISSUE TITLE
Issue in Input 

### ISSUE THREAD

**Issue by nthakor** [iwyoo/LSTM-autoencoder#1]
I am trying to predict clear signal from a noisy signal. The data is time-series data. I am having difficulties in understanding how to give me input to the model. Can you explain your method for input in test.py? I am unclear about the dimensions and what parameters like elem_num, step_num, etc. signifies?

**Comment by iwyoo** [comment]
elem_num means that the input dimension of each cell. For example, if you want to give RGB image pixel then it should be 3 (R, G, B). In test.py, I used 1 to give 1 number for each cell.

step_num means how many times your LSTM is unfolded. It depends on your choice. If you want to give 10 step signals, then you should define it as 10. In test.py, I used 8 sequential numbers (8,9,10,...,15).

p_inputs is a list of tensors. The length should be same as step_num and dimension of each tensor should be [batch_size, elem_num].

There are some options in the constructor. 
```
#LSTMAutoencoder.py
def __init__(self, hidden_num, inputs, 
    cell=None, optimizer=None, reverse=True, 
    decode_without_input=False):
```
You can check the original paper(http://arxiv.org/abs/1502.04681). reverse is a boolean to order reconstruct sequence reverse or not. decode_without_input is wiring condition of reconstruction.  (See Figure 3, v4 and v5). However, I recommend you to use it with default argument as I used in test.py.
