### ISSUE TITLE
How to get encode weight and coding results?

### ISSUE THREAD

**Issue by Alisaincd** [iwyoo/LSTM-autoencoder#2]
Hi,I am interested in this project.But I got two questions:
1. How can I get the encode weight after training?
2.  How can I get the encode result but not to decode? Because I want to use the encoding result to do something.
I will really appreciate it if you can answer the questions. Thank you !!

**Comment by iwyoo** [comment]
You can get enc_state by referencing it.
```enc_state = sess.run(ae.enc_state) ``` gives you the encode state of the LSTM-autoencoder.
I have not implemented to get the variables in the model. However, it looks that there is more powerful way to do that. Check http://stackoverflow.com/questions/40325012/get-value-of-weights-and-bias-from-rnn-cell.
