### ISSUE TITLE
Encoder Decoder relation ?

### ISSUE THREAD

**Issue by sooroosh** [iwyoo/LSTM-autoencoder#4]
In this implementation you are generating z.codes by the encoder but you never use them again. However, as far as I remember the idea behind the autoencoders is to decode the hidden representation of the encoder part by the decoder part to reconstruct the input. What I see in this code is that for decoding you only take the final state of the encoder part and reconstruct the input by starting from a zero initialization. However, I am not sure whether there is something I am missing to understand this code.

**Comment by iwyoo** [comment]
Yes, as you say, `z_codes` is more like an temporary outputs of the encoder LSTM. (I don't remember why I named like that.)
I think I used that variable for debug, but anyway, it is useless.
In the original paper, the decoder only uses encoder's state for the decoding. Therefore, you can think actual latent variable is `enc_state`.
